// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VentasNet.Infra.Data;

public partial class Venta
{
    public int IdVenta { get; set; }

    public int NumCbte { get; set; }

    public string NombreCli { get; set; }

    public DateTime? Fecha { get; set; }

    public bool? Estado { get; set; }
}