// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using VentasNET.Entity.Data.Configurations;
using VentasNET.Entity.Models;
#nullable disable

namespace VentasNET.Entity.Data;

public partial class VentasNetContext : DbContext
{
    public VentasNetContext(DbContextOptions<VentasNetContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Cliente> Cliente { get; set; }

    public virtual DbSet<Comprobante> Comprobante { get; set; }

    public virtual DbSet<Financiacion> Financiacion { get; set; }

    public virtual DbSet<FormasDePago> FormasDePago { get; set; }

    public virtual DbSet<MetodosPago> MetodosPago { get; set; }

    public virtual DbSet<MovimientoDeComprobantes> MovimientoDeComprobantes { get; set; }

    public virtual DbSet<MovimientoDeProveedores> MovimientoDeProveedores { get; set; }

    public virtual DbSet<Producto> Producto { get; set; }

    public virtual DbSet<Proveedor> Proveedor { get; set; }

    public virtual DbSet<Stock> Stock { get; set; }

    public virtual DbSet<Usuario> Usuario { get; set; }

    public virtual DbSet<Venta> Venta { get; set; }

    public virtual DbSet<VwComprobantes> VwComprobantes { get; set; }

    public virtual DbSet<VwUsuario> VwUsuario { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfigurationsFromAssembly(typeof(VentasNetContext).Assembly);

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
