// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using VentasNET.Entity.Data;
using VentasNET.Entity.Models;

namespace VentasNET.Entity.Data.Configurations
{
    public partial class MovimientoDeComprobantesConfiguration : IEntityTypeConfiguration<MovimientoDeComprobantes>
    {
        public void Configure(EntityTypeBuilder<MovimientoDeComprobantes> entity)
        {
            entity.Property(e => e.Descuento).HasColumnType("decimal(16, 2)");
            entity.Property(e => e.Importe).HasColumnType("decimal(16, 2)");
            entity.Property(e => e.Total).HasColumnType("decimal(16, 2)");

            entity.HasOne(d => d.IdComprobanteNavigation).WithMany(p => p.MovimientoDeComprobantes)
            .HasForeignKey(d => d.IdComprobante)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_MovimientoDeComprobantes_Comprobante");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<MovimientoDeComprobantes> entity);
    }
}
