// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VentasNET.Entity.Models;

public partial class Comprobante
{
    public int IdComprobante { get; set; }

    public string Nombre { get; set; }

    public string NombreCorto { get; set; }

    public string Descripcion { get; set; }

    public int? NroCbte { get; set; }

    public int? NroSucursal { get; set; }

    public DateTime? FechaMovimiento { get; set; }

    public virtual ICollection<MovimientoDeComprobantes> MovimientoDeComprobantes { get; set; } = new List<MovimientoDeComprobantes>();

    public virtual ICollection<Stock> Stock { get; set; } = new List<Stock>();
}