// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VentasNET.Entity.Models;

public partial class Financiacion
{
    public int Id { get; set; }

    public string Descripcion { get; set; }

    public string Codigo { get; set; }

    public string Porcentaje { get; set; }
}