// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VentasNET.Entity.Models;

public partial class MovimientoDeProveedores
{
    public int Id { get; set; }

    public string Comprobante { get; set; }

    public DateTime FechaComprobante { get; set; }

    public decimal ImporteTotal { get; set; }

    public decimal? Descuentos { get; set; }

    public byte[] FechaMovimiento { get; set; }

    public int IdUsuario { get; set; }
}